name = "preloaded_state"
compatibility_date = "2025-11-18"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "preloaded_state_db"
database_id = "8dea5a32-2294-4a9e-8fa3-b01a15f39fce"
